import {
  importLocalModelRequestSchema,
  localModelInventorySchema,
  localModelSelectorRequestSchema,
  localModelStatusSchema,
  localModelTestResultSchema,
  refreshLocalModelsRequestSchema,
  removeLocalModelRequestSchema,
  updateLocalModelRequestSchema,
} from "./local-models.js";
import {
  deleteLocalRuntimeRequestSchema,
  localRuntimeCatalogSchema,
  localRuntimeProbeSchema,
  probeLocalRuntimeRequestSchema,
  upsertLocalRuntimeRequestSchema,
} from "./local-runtimes.js";
import {
  providerCatalogSchema,
  upsertCustomProviderRequestSchema,
  upsertModelDefinitionRequestSchema,
} from "./providers.js";
import { z } from "zod";
import { defineOperation } from "../../operations/definition.js";

const emptyParamsSchema = z.object({}).optional();
const deleteProviderParamsSchema = z.object({ id: z.string().min(1) });
const deleteModelParamsSchema = z.object({
  provider: z.string().min(1),
  modelId: z.string().min(1),
});

export const providersOperationDefinitions = [
  defineOperation(
    "providerCatalog.get",
    emptyParamsSchema,
    providerCatalogSchema,
    "read",
    "none",
    ["workbench_server"] as const,
    "operation.providerCatalog.get",
  ),
  defineOperation(
    "providerCatalog.custom.upsert",
    upsertCustomProviderRequestSchema,
    providerCatalogSchema,
    "mutation",
    "recommended",
    ["workbench_server"] as const,
    "operation.providerCatalog.custom.upsert",
  ),
  defineOperation(
    "providerCatalog.custom.delete",
    deleteProviderParamsSchema,
    providerCatalogSchema,
    "mutation",
    "recommended",
    ["workbench_server"] as const,
    "operation.providerCatalog.custom.delete",
  ),
  defineOperation(
    "providerCatalog.model.upsert",
    upsertModelDefinitionRequestSchema,
    providerCatalogSchema,
    "mutation",
    "recommended",
    ["workbench_server"] as const,
    "operation.providerCatalog.model.upsert",
  ),
  defineOperation(
    "providerCatalog.model.delete",
    deleteModelParamsSchema,
    providerCatalogSchema,
    "mutation",
    "recommended",
    ["workbench_server"] as const,
    "operation.providerCatalog.model.delete",
  ),
  defineOperation(
    "localRuntime.list",
    emptyParamsSchema,
    localRuntimeCatalogSchema,
    "read",
    "none",
    ["workbench_server"] as const,
    "operation.localRuntime.list",
  ),
  defineOperation(
    "localRuntime.upsert",
    upsertLocalRuntimeRequestSchema,
    localRuntimeCatalogSchema,
    "mutation",
    "recommended",
    ["workbench_server"] as const,
    "operation.localRuntime.upsert",
  ),
  defineOperation(
    "localRuntime.delete",
    deleteLocalRuntimeRequestSchema,
    localRuntimeCatalogSchema,
    "mutation",
    "recommended",
    ["workbench_server"] as const,
    "operation.localRuntime.delete",
  ),
  defineOperation(
    "localRuntime.probe",
    probeLocalRuntimeRequestSchema,
    localRuntimeProbeSchema,
    "read",
    "none",
    ["workbench_server"] as const,
    "operation.localRuntime.probe",
  ),
  defineOperation(
    "localModel.list",
    emptyParamsSchema,
    localModelInventorySchema,
    "read",
    "none",
    ["workbench_server"] as const,
    "operation.localModel.list",
  ),
  defineOperation(
    "localModel.refresh",
    refreshLocalModelsRequestSchema,
    localModelInventorySchema,
    "read",
    "none",
    ["workbench_server"] as const,
    "operation.localModel.refresh",
  ),
  defineOperation(
    "localModel.import",
    importLocalModelRequestSchema,
    localModelInventorySchema,
    "mutation",
    "recommended",
    ["workbench_server"] as const,
    "operation.localModel.import",
  ),
  defineOperation(
    "localModel.update",
    updateLocalModelRequestSchema,
    localModelInventorySchema,
    "mutation",
    "recommended",
    ["workbench_server"] as const,
    "operation.localModel.update",
  ),
  defineOperation(
    "localModel.remove",
    removeLocalModelRequestSchema,
    localModelInventorySchema,
    "mutation",
    "recommended",
    ["workbench_server"] as const,
    "operation.localModel.remove",
  ),
  defineOperation(
    "localModel.test",
    localModelSelectorRequestSchema,
    localModelTestResultSchema,
    "read",
    "none",
    ["workbench_server"] as const,
    "operation.localModel.test",
  ),
  defineOperation(
    "localModel.status",
    localModelSelectorRequestSchema,
    localModelStatusSchema,
    "read",
    "none",
    ["workbench_server"] as const,
    "operation.localModel.status",
  ),
  defineOperation(
    "localModel.load",
    localModelSelectorRequestSchema,
    localModelStatusSchema,
    "mutation",
    "recommended",
    ["workbench_server"] as const,
    "operation.localModel.load",
  ),
  defineOperation(
    "localModel.unload",
    localModelSelectorRequestSchema,
    localModelStatusSchema,
    "mutation",
    "recommended",
    ["workbench_server"] as const,
    "operation.localModel.unload",
  ),
] as const;
