import assert from "node:assert/strict";
import { mkdtemp, mkdir, readFile, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import test from "node:test";
import {
  assertReleaseVersion,
  readRustReleaseVersions,
  setWorkspaceVersion,
} from "./release-version.mjs";
import {
  assertWorkspaceVersionsMatch,
  versionLockedPackages,
} from "./workspace-packages.mjs";

async function createFixture() {
  const root = await mkdtemp(join(tmpdir(), "nerve-release-version-"));
  await mkdir(join(root, "packages", "alpha"), { recursive: true });
  await mkdir(join(root, "packages", "website"), { recursive: true });
  await mkdir(join(root, "packages", "native", "native"), {
    recursive: true,
  });
  await writeFile(
    join(root, "package.json"),
    `${JSON.stringify({ name: "root", version: "1.0.0", private: true }, null, 2)}\n`,
  );
  await writeFile(
    join(root, "packages", "alpha", "package.json"),
    `${JSON.stringify({ name: "alpha", version: "1.0.0", marker: "kept" }, null, 2)}\n`,
  );
  await writeFile(
    join(root, "packages", "website", "package.json"),
    `${JSON.stringify({ name: "website", version: "0.9.0" }, null, 2)}\n`,
  );
  await writeFile(
    join(root, "packages", "native", "package.json"),
    `${JSON.stringify({ name: "@nervekit/native", version: "1.0.0" }, null, 2)}\n`,
  );
  await writeFile(
    join(root, "packages", "native", "native", "Cargo.toml"),
    `[package]\nname = "nerve-native"\nversion = "1.0.0"\nedition = "2024"\n\n[dependencies]\nlibc = "0.2.180"\n\n[package.metadata.fixture]\nversion = "preserved"\n`,
  );
  await writeFile(
    join(root, "Cargo.lock"),
    `# This file is automatically @generated by Cargo.\nversion = 4\n\n[[package]]\nname = "libc"\nversion = "0.2.180"\n\n[[package]]\nname = "nerve-native"\nversion = "1.0.0"\ndependencies = [\n "libc",\n]\n`,
  );
  return root;
}

async function completeVersionLockedFixture() {
  const root = await createFixture();
  for (const directory of versionLockedPackages) {
    const path = join(root, "packages", directory, "package.json");
    try {
      await readFile(path);
    } catch {
      await mkdir(join(root, "packages", directory), { recursive: true });
      await writeFile(
        path,
        `${JSON.stringify({ name: `@nervekit/${directory}`, version: "1.0.0" }, null, 2)}\n`,
      );
    }
  }
  return root;
}

async function readJson(path) {
  return JSON.parse(await readFile(path, "utf8"));
}

test("accepts stable and prerelease versions", () => {
  for (const version of ["0.23.0", "1.2.3-rc.1", "10.0.0-beta-feature.2"]) {
    assert.equal(assertReleaseVersion(version), version);
  }
});

test("rejects non-canonical or unsupported versions", () => {
  for (const version of [
    "v1.2.3",
    "1.2",
    "01.2.3",
    "1.2.3-rc.01",
    "1.2.3+build.1",
    "1.2.3-",
  ]) {
    assert.throws(
      () => assertReleaseVersion(version),
      /Invalid release version/,
    );
  }
});

test("updates the root and every package manifest", async (context) => {
  const root = await createFixture();
  context.after(() => rm(root, { recursive: true, force: true }));

  const changedPaths = await setWorkspaceVersion(root, "1.1.0-rc.1");
  assert.deepEqual(changedPaths, [
    "package.json",
    join("packages", "alpha", "package.json"),
    join("packages", "native", "package.json"),
    join("packages", "website", "package.json"),
    join("packages", "native", "native", "Cargo.toml"),
    "Cargo.lock",
  ]);

  const rootManifest = await readJson(join(root, "package.json"));
  const alphaManifest = await readJson(
    join(root, "packages", "alpha", "package.json"),
  );
  const websiteManifest = await readJson(
    join(root, "packages", "website", "package.json"),
  );
  assert.equal(rootManifest.version, "1.1.0-rc.1");
  assert.equal(alphaManifest.version, "1.1.0-rc.1");
  assert.equal(alphaManifest.marker, "kept");
  assert.equal(websiteManifest.version, "1.1.0-rc.1");
  assert.deepEqual(await readRustReleaseVersions(root), {
    manifest: "1.1.0-rc.1",
    lockfile: "1.1.0-rc.1",
  });
  assert.match(
    await readFile(
      join(root, "packages", "native", "native", "Cargo.toml"),
      "utf8",
    ),
    /edition = "2024"[\s\S]*libc = "0\.2\.180"[\s\S]*version = "preserved"/,
  );
  assert.match(
    await readFile(join(root, "Cargo.lock"), "utf8"),
    /name = "libc"\nversion = "0\.2\.180"/,
  );

  assert.deepEqual(await setWorkspaceVersion(root, "1.1.0-rc.1"), []);
});

test("release consistency includes Cargo manifest and lock versions", async (context) => {
  const root = await completeVersionLockedFixture();
  context.after(() => rm(root, { recursive: true, force: true }));
  assert.equal(await assertWorkspaceVersionsMatch(root), "1.0.0");

  const lockPath = join(root, "Cargo.lock");
  const lockfile = await readFile(lockPath, "utf8");
  await writeFile(
    lockPath,
    lockfile.replace(
      'name = "nerve-native"\nversion = "1.0.0"',
      'name = "nerve-native"\nversion = "0.9.0"',
    ),
  );
  await assert.rejects(
    assertWorkspaceVersionsMatch(root),
    /Cargo\.lock \(nerve-native\): 0\.9\.0/,
  );
});

test("rejects an ambiguous native lockfile entry", async (context) => {
  const root = await createFixture();
  context.after(() => rm(root, { recursive: true, force: true }));
  const lockPath = join(root, "Cargo.lock");
  const lockfile = await readFile(lockPath, "utf8");
  await writeFile(
    lockPath,
    `${lockfile}\n[[package]]\nname = "nerve-native"\nversion = "1.0.0"\n`,
  );

  await assert.rejects(
    setWorkspaceVersion(root, "1.1.0"),
    /exactly one nerve-native package entry; found 2/,
  );
});

test("rejects a Cargo manifest for another package", async (context) => {
  const root = await createFixture();
  context.after(() => rm(root, { recursive: true, force: true }));
  const manifestPath = join(root, "packages", "native", "native", "Cargo.toml");
  const manifest = await readFile(manifestPath, "utf8");
  await writeFile(
    manifestPath,
    manifest.replace('name = "nerve-native"', 'name = "other"'),
  );

  await assert.rejects(
    setWorkspaceVersion(root, "1.1.0"),
    /expected "nerve-native"/,
  );
});
