import type {
  PermissionTargetKind,
  StaticToolRisk,
  ToolKind,
} from "@nervekit/contracts/permissions";
import type { ToolName } from "@nervekit/contracts/tools";

export interface ToolPermissionMetadata {
  kind: ToolKind;
  groups: readonly string[];
  baseRisk: StaticToolRisk;
  primaryArguments: readonly string[];
  targetKinds: readonly PermissionTargetKind[];
  primaryTargetComplete: boolean;
}

const metadata = {
  read: m("filesystem", "fileInspection", "read", ["path"], ["path"], true),
  bash: m("command", "shell", "unknown", ["command"], ["whole_tool"], true),
  python_exec: m(
    "code",
    "python",
    "unknown",
    ["code", "path"],
    ["whole_tool"],
    true,
  ),
  edit: m("filesystem", "fileEditing", "write", ["path"], ["path"], true),
  write: m("filesystem", "fileEditing", "write", ["path"], ["path"], true),
  grep: m(
    "filesystem",
    "fileInspection",
    "read",
    ["paths", "path"],
    ["path"],
    false,
  ),
  find: m("filesystem", "fileInspection", "read", ["path"], ["path"], true),
  ls: m("filesystem", "fileInspection", "read", ["path"], ["path"], true),
  ask_user: m(
    "interaction",
    "input",
    "interaction",
    ["question"],
    ["whole_tool"],
    true,
  ),
  todos_set: m("interaction", "todos", "interaction", [], ["whole_tool"], true),
  todos_get: m("interaction", "todos", "read", [], ["whole_tool"], true),
  web_search: m("network", "web", "network", ["query"], ["whole_tool"], true),
  web_fetch: m("network", "web", "network", ["url"], ["url"], true),
  explain_image: m("network", "vision", "network", ["path"], ["path"], true),
  jira_search_users: m(
    "integration",
    "jira",
    "network",
    ["query"],
    ["whole_tool"],
    true,
  ),
  jira_search_issues: m(
    "integration",
    "jira",
    "network",
    ["jql"],
    ["whole_tool"],
    true,
  ),
  jira_get_issue: m(
    "integration",
    "jira",
    "network",
    ["issue_key"],
    ["whole_tool"],
    true,
  ),
  jira_get_project: m(
    "integration",
    "jira",
    "network",
    ["project_key"],
    ["whole_tool"],
    true,
  ),
  jira_search_boards: m(
    "integration",
    "jira",
    "network",
    ["project_key", "name"],
    ["whole_tool"],
    true,
  ),
  jira_get_board: m(
    "integration",
    "jira",
    "network",
    ["board_id"],
    ["whole_tool"],
    true,
  ),
  jira_get_sprint: m(
    "integration",
    "jira",
    "network",
    ["sprint_id"],
    ["whole_tool"],
    true,
  ),
  jira_download_attachment: m(
    "integration",
    "jira",
    "network",
    ["attachment_id"],
    ["whole_tool"],
    true,
  ),
  jira_create_issue: m(
    "integration",
    "jira",
    "write",
    ["project_key"],
    ["whole_tool"],
    true,
  ),
  jira_update_issue: m(
    "integration",
    "jira",
    "write",
    ["issue_key"],
    ["whole_tool"],
    true,
  ),
  jira_transition_issue: m(
    "integration",
    "jira",
    "write",
    ["issue_key"],
    ["whole_tool"],
    true,
  ),
  jira_manage_comment: m(
    "integration",
    "jira",
    "destructive",
    ["comment_id", "issue_key"],
    ["whole_tool"],
    true,
  ),
  jira_manage_worklog: m(
    "integration",
    "jira",
    "destructive",
    ["worklog_id", "issue_key"],
    ["whole_tool"],
    true,
  ),
  jira_manage_issue_link: m(
    "integration",
    "jira",
    "destructive",
    ["link_id", "issue_key"],
    ["whole_tool"],
    true,
  ),
  jira_manage_attachment: m(
    "integration",
    "jira",
    "destructive",
    ["attachment_id", "issue_key"],
    ["path", "whole_tool"],
    false,
  ),
  jira_manage_sprint: m(
    "integration",
    "jira",
    "destructive",
    ["sprint_id", "board_id"],
    ["whole_tool"],
    true,
  ),
  jira_manage_backlog: m(
    "integration",
    "jira",
    "write",
    ["issue_key"],
    ["whole_tool"],
    true,
  ),
  confluence_search_spaces: m(
    "integration",
    "confluence",
    "network",
    ["keys", "ids"],
    ["whole_tool"],
    true,
  ),
  confluence_search_pages: m(
    "integration",
    "confluence",
    "network",
    ["cql", "query", "space_key", "space_id", "title"],
    ["whole_tool"],
    true,
  ),
  confluence_get_page: m(
    "integration",
    "confluence",
    "network",
    ["page_id"],
    ["whole_tool"],
    true,
  ),
  confluence_download_page: m(
    "integration",
    "confluence",
    "network",
    ["page_id"],
    ["whole_tool"],
    true,
  ),
  confluence_create_page: m(
    "integration",
    "confluence",
    "write",
    ["space_id", "space_key", "parent_id", "page_file"],
    ["path", "whole_tool"],
    false,
  ),
  confluence_update_page: m(
    "integration",
    "confluence",
    "write",
    ["page_id", "page_file"],
    ["path", "whole_tool"],
    false,
  ),
  confluence_manage_comment: m(
    "integration",
    "confluence",
    "destructive",
    ["comment_id", "page_id"],
    ["whole_tool"],
    true,
  ),
  confluence_manage_page: m(
    "integration",
    "confluence",
    "destructive",
    ["page_id"],
    ["whole_tool"],
    true,
  ),
  confluence_manage_label: m(
    "integration",
    "confluence",
    "write",
    ["page_id"],
    ["whole_tool"],
    true,
  ),
  confluence_manage_restriction: m(
    "integration",
    "confluence",
    "destructive",
    ["page_id"],
    ["whole_tool"],
    true,
  ),
  confluence_manage_attachment: m(
    "integration",
    "confluence",
    "destructive",
    ["attachment_id", "page_id"],
    ["path", "whole_tool"],
    false,
  ),
  task_start: m(
    "orchestration",
    "taskManagement",
    "unknown",
    ["command"],
    ["whole_tool"],
    true,
  ),
  task_status: m(
    "orchestration",
    "taskManagement",
    "read",
    ["tasks", "status"],
    ["whole_tool"],
    true,
  ),
  task_logs: m(
    "orchestration",
    "taskManagement",
    "read",
    ["task"],
    ["whole_tool"],
    true,
  ),
  task_control: m(
    "orchestration",
    "taskManagement",
    "unknown",
    ["task"],
    ["whole_tool"],
    true,
  ),
  explore: m("orchestration", "explore", "agent_spawn", [], ["agent"], true),
  plan_mode_enter: m(
    "orchestration",
    "planMode",
    "interaction",
    ["reason"],
    ["whole_tool"],
    true,
  ),
  plan_mode_present: m(
    "orchestration",
    "planMode",
    "interaction",
    ["file_path"],
    ["path"],
    true,
  ),
  plan_mode_force_exit: m(
    "orchestration",
    "planMode",
    "interaction",
    ["reason"],
    ["whole_tool"],
    true,
  ),
} satisfies Record<ToolName, ToolPermissionMetadata>;

function m(
  kind: ToolKind,
  group: string,
  baseRisk: StaticToolRisk,
  primaryArguments: readonly string[],
  targetKinds: readonly PermissionTargetKind[],
  primaryTargetComplete: boolean,
): ToolPermissionMetadata {
  return Object.freeze({
    kind,
    groups: Object.freeze([group]),
    baseRisk,
    primaryArguments: Object.freeze(primaryArguments),
    targetKinds: Object.freeze(targetKinds),
    primaryTargetComplete,
  });
}

export const toolPermissionMetadata: Readonly<
  Record<ToolName, ToolPermissionMetadata>
> = Object.freeze(metadata);

export function permissionMetadataForTool(
  name: ToolName,
): ToolPermissionMetadata {
  return toolPermissionMetadata[name];
}
